#!/bin/bash
#
# $Id: dbswitch,v 1.3 2003/10/08 07:08:31 tuxmonkey Exp $
#
# This is a very basic script to convert the database
# schema for issue-tracker from a postgresql schema
# to a mysql schema and back again
#

if [ -z $1 ]
then
  echo "Syntax: $0 <filename>"
  exit;
fi

GREP=`grep AUTO_INCREMENT $1`

if [ -z "$GREP" ]
then
  # Convert from PostgreSQL to MySQL
  perl -pi -e 's/TEXT/MEDIUMTEXT/g' $1
  perl -pi -e 's/SERIAL/INTEGER\ AUTO_INCREMENT/g' $1
  CONVERT="(PostgreSQL -> MySQL)"
else
  # Convert from MySQL to PostgreSQL
  perl -pi -e 's/MEDIUMTEXT/TEXT/g' $1
  perl -pi -e 's/INTEGER\ AUTO_INCREMENT/SERIAL/g' $1
  CONVERT="(MySQL -> PostgreSQL)"
fi

echo "File converted. $CONVERT"
exit;
  
